### ISSUE TITLE
Fjöldi liða í "skipta í lið"

### ISSUE THREAD

**Issue by Bjarkias** [olitomas/vantaribolta#1]
Það væri gott að geta skilgreint fjölda liða sem á að skipta í.
Nóg væri að geta ýta á + eða - í fjöldi liða  
Þegar 13+ manns eru komnir í körfuboltaviðburð finnst mínum hóp betra að skipta í 3 lið

**Comment by olitomas** [comment]
Fékkst forgang fyrst þú varst fyrstur að gera issue....komið!
